name: GitHub Actions - Push General
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
    - master
    - develop
    # branches-ignore:
    # - 'release/**'
    paths:
      - '**.txt'
    # Ambas condições de branch e path tem que ser satisfeitas para o workflow 
    #ser acionado
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário PUSH WORKFLOW"